apiVersion: 1

datasources:
  - name: InfluxDB ($INFLUXDB_DB)
    type: influxdb
    access: proxy
    database: $INFLUXDB_DB
    # HTTP used here as TLS encryption is terminated on the reverse proxy (Traefik)
    url: http://$INFLUXDB_DOCKER_CONTAINER_NAME:$INFLUXDB_PORT
    secureJsonData:
      token: $INFLUXDB_INIT_ADMIN_TOKEN
    jsonData:
      version: Flux
      organization: $INFLUXDB_INIT_ORG
      defaultBucket: $INFLUXDB_INIT_BUCKET
      tlsSkipVerify: true
    isDefault: true
    editable: true
